from app.repositories.gestion_usuario.rol.rol_repository import RolRepository
from app.repositories.gestion_usuario.usuario.usuario_repository import UsuarioRepository
from app.repositories.gestion_usuario.permisos_repository import PermisosRepository